MV.Factory.Climas/MV.Factory.SitioClimas/Models/Clima/ClimaConsultaModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MV.Factory.SitioClimas.Models.Clima
{
    public class ClimaConsultaModel
    {
        [Range(1,9999999, ErrorMessage = "Debe seleccionar Zona Clima")]                
        public int IdZonaClima { get; set; }

        [Display(Name = "Incluir histórico")]
        public bool DebeIncluirHistorico { get; set; }

        [Required(ErrorMessage ="Debe ingresar una fecha")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime FechaConsulta { get; set; }
    }
}

MV.Factory.Climas/MV.Factory.SitioClimas/Models/Clima/ClimaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MV.Factory.SitioClimas.Models.Clima
{
    public class ClimaModel
    {
        public string ZonaClimaNombre { get; set; }
        public string Pais { get; set; }
        public string CiudadNombreCompleto { get; set; }
        public decimal Temperatura { get; set; }
        public decimal SensacionTermica { get; set; }
        public DateTime FechaConsulta { get; set; }
    }
}

MV.Factory.Climas/MV.Factory.SitioClimas/Models/Clima/ClimasViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MV.Factory.Domain.Implementaciones;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MV.Factory.SitioClimas.Models.Clima
{
    public class ClimasViewModel
    {
        public ClimaConsultaModel ClimaConsultaModel { get; set; }
        public ClimaModel ClimaModel { get; set; }

        public IList<ClimaModel> HistorialConsultaClima { get; set; }

        public IList<SelectListItem> ZonasClimas { get; set; }

        public void IniciarValores(IList<ZonaClima> zonasClimas)
        {
            ZonasClimas = new List<SelectListItem>();

            ZonasClimas.Add(
                    new SelectListItem
                    {
                        Text = "Seleccione la Ciudad",
                        Value = 0.ToString(),
                    }
                );

            foreach (var zonaClima in zonasClimas)
            {
                ZonasClimas.Add(
                    new SelectListItem
                    {
                        Text = $"{zonaClima.Nombre} - {zonaClima.Pais}",
                        Value = zonaClima.ID.ToString(),
                        Selected = ClimaConsultaModel?.IdZonaClima == zonaClima.ID,
                    }
                );
            }
        }
    }
}

MV.Factory.Climas/MV.Factory.SitioClimas/Models/ErrorViewModel.cs
using System;

namespace MV.Factory.SitioClimas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MV.Factory.Climas/MV.Factory.SitioClimas/Controllers/ClimaController.cs
using Microsoft.AspNetCore.Mvc;
using MV.Factory.Domain.Implementaciones;
using MV.Factory.SitioClimas.ConsumidoresAPIs;
using MV.Factory.SitioClimas.Models.Clima;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MV.Factory.SitioClimas.Controllers
{
    public class ClimaController : Controller
    {
        public async Task<IActionResult> Index()
        {
            try
            {
                var vm = new ClimasViewModel();
                vm.ClimaModel = new ClimaModel();
                vm.ClimaConsultaModel = new ClimaConsultaModel
                {
                    FechaConsulta = DateTime.Now.Date,
                };

                var zonasClimas = await ConsumidorAPIClimas.ObtenerZonasClimas();

                vm.IniciarValores(zonasClimas);

                return View(vm);
            }
            catch (Exception ex)
            {
                Log.Error($"Hubo un error al ingresar a la pagina de clima action {nameof(Index)} error {ex.Message}");
                return RedirectToAction("Error", "Home");
            }            
        }

        public async Task<IActionResult> ConsultarClima(ClimaConsultaModel climaConsultaModel)
        {
            try
            {
                var vm = new ClimasViewModel();
                vm.ClimaConsultaModel = climaConsultaModel;
                vm.ClimaModel = new ClimaModel();

                var zonasClimas = await ConsumidorAPIClimas.ObtenerZonasClimas();
                vm.IniciarValores(zonasClimas);

                
                if (ModelState.IsValid)
                {
                    var openWeatherMapModelModel = await ConsumidorAPIOpenWeatherMap.ObtenerDatosClima(climaConsultaModel.IdZonaClima);

                    vm.ClimaModel.Temperatura = openWeatherMapModelModel.OpenWeatherMapPropiedadPrincipal.TemperaturaEnGrado;
                    vm.ClimaModel.SensacionTermica = openWeatherMapModelModel.OpenWeatherMapPropiedadPrincipal.SensacionTermicaEnGrado;

                    var historialesConsultasZonasClimas = await ConsumidorAPIClimas.ObtenerHistorialConsultaClima(climaConsultaModel.IdZonaClima, climaConsultaModel.FechaConsulta);

                    vm.HistorialConsultaClima = historialesConsultasZonasClimas.Select(p => new ClimaModel
                    {
                        ZonaClimaNombre = p.ZonaClima.Nombre,
                        Pais = p.ZonaClima.Pais,
                        Temperatura = p.Temperatura,
                        SensacionTermica = p.SensacionTermica,
                        FechaConsulta = p.FechaConsulta,
                    }).ToList();

                    if (climaConsultaModel.DebeIncluirHistorico)
                    {
                        var historialConsultaClima = new HistorialConsultaClima
                        {
                            FechaConsulta = DateTime.Now,
                            IdZonaClima = climaConsultaModel.IdZonaClima,
                            Temperatura = vm.ClimaModel.Temperatura,
                            SensacionTermica = vm.ClimaModel.SensacionTermica,
                        };

                        await ConsumidorAPIClimas.AgregarHistorialConsultaClima(historialConsultaClima);
                    }                    
                }

                if (vm.ClimaConsultaModel?.IdZonaClima > 0)
                {
                    var zonaClima = await ConsumidorAPIClimas.ObtenerZonaClima(vm.ClimaConsultaModel.IdZonaClima);

                    vm.ClimaModel.CiudadNombreCompleto = $"{zonaClima.Nombre}, {zonaClima.Pais}";
                }

                return View("Index", vm);
            }
            catch (Exception ex)
            {
                Log.Error($"Hugo un error al realizar la consulta de climas action {nameof(ConsultarClima)} error {ex.Message}");
                return RedirectToAction("Error","Home");
            }            
        }
    }
}

MV.Factory.Climas/MV.Factory.SitioClimas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MV.Factory.SitioClimas.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MV.Factory.SitioClimas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Acerca()
        {            
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MV.Factory.Climas/MV.Factory.SitioClimas/Views/Clima/Index.cshtml
@model MV.Factory.SitioClimas.Models.Clima.ClimasViewModel
@{
    ViewData["Title"] = " Climas";
}

<div class="row">
    <h1 class="ml-3">Climas</h1>
</div>

@using (Html.BeginForm("ConsultarClima", "Clima", FormMethod.Post, new { @class = "mb-1" }))
{
    <div class="form-row">
        <div class="col-12 col-sm-4 my-1">
            @Html.DropDownListFor(m => m.ClimaConsultaModel.IdZonaClima, Model.ZonasClimas, new { @class = "custom-select mr-sm-4" })
            <small class="error">@Html.ValidationMessageFor(m => m.ClimaConsultaModel.IdZonaClima) </small>
        </div>
        <div class="col-12 col-sm-2 my-1">
            <div class="custom-control custom-checkbox mr-sm-2">
                @Html.CheckBoxFor(m => m.ClimaConsultaModel.DebeIncluirHistorico, new { @class = "custom-control-input" })
                @*<input type="checkbox" class="custom-control-input" id="customControlAutosizing">*@
                @Html.LabelFor(m => m.ClimaConsultaModel.DebeIncluirHistorico, new { @class = "custom-control-label" })
            </div>
        </div>
        <div class="col-12 col-sm-3 my-1">
            @Html.LabelFor(m => m.ClimaConsultaModel.FechaConsulta, new { @class = "mr-sm-4" })

            @Html.TextBoxFor(m => m.ClimaConsultaModel.FechaConsulta, "{0:dd/MM/yyyy}", new { @readonly = "readonly", id = "txtFechaConsulta" })

            <small class="error">@Html.ValidationMessageFor(m => m.ClimaConsultaModel.FechaConsulta) </small>
        </div>
        <div class="col-12 col-sm-3 my-1">
            <button type="submit" class="btn btn-primary">Consultar</button>
        </div>
    </div>
}

<div class="row">
    <div class="col-2">Ciudad:</div>
    <div class="col-10">@Model.ClimaModel.CiudadNombreCompleto</div>
</div>

<div class="row">
    <div class="col-2">Clima:</div>
    <div class="col-10">@Model.ClimaModel.Temperatura.ToString("n2") ° - Sensacción Térmica: @Model.ClimaModel.SensacionTermica.ToString("n2") °</div>
</div>

<div class="row mt-5 mr-1 ml-1 ">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Pais</th>
                <th>Ciudad</th>
                <th>Clima</th>
                <th>Sensación Térmica</th>
                <th>Fecha</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.HistorialConsultaClima != null)
            {
                foreach (var historial in Model.HistorialConsultaClima)
                {
                    <tr>
                        <td>@historial.Pais</td>
                        <td>@historial.ZonaClimaNombre</td>
                        <td>@historial.Temperatura.ToString("n2") °</td>
                        <td>@historial.SensacionTermica.ToString("n2") °</td>
                        <td>@historial.FechaConsulta.ToString("mm/MM/yyyy HH:mm")</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@section scripts {
    <script type="text/javascript">
        $(function () {
            $('#txtFechaConsulta').datepicker({
                changeMonth: true,
                changeYear: true,
                format: "dd/mm/yyyy",
                language: "es"
            });
        });
    </script>
} 

MV.Factory.Climas/MV.Factory.SitioClimas/Views/Home/Acerca.cshtml
@{
    ViewData["Title"] = "Acerca";
}


<h1>Contenido</h1>

<p>Proyecto de prueba técnica. Caso de uso, realizar el muestreo de datos de climas de determinadas Zonas y guardar el Histórico de consultas.   </p>

MV.Factory.Climas/MV.Factory.SitioClimas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MV.Factory.Climas/MV.Factory.SitioClimas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - V1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Clima" asp-action="Index">Climas V1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clima" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Acerca</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MV.Factory.SitioClimas - <a asp-area="" asp-controller="Home" asp-action="Acerca">Acerca</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker-extension-es.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>